---
version: "2.1"
services:
  minetest:
    image: registry.gitlab.com/minetest/minetest/server:latest
    container_name: minetest
    entrypoint: "/usr/local/bin/minetestserver"
    command: "--config /etc/minetest/minetest.conf --gameid nodecore"
    volumes:
      - /home/docker/minetest/worlds:/usr/local/share/minetest/worlds
      - /home/docker/minetest/games:/usr/local/share/minetest/games
    ports:
      - 30000:30000/udp
    restart: unless-stopped
