---
version: "2.1"
services:
  minetest:
    image: registry.gitlab.com/minetest/minetest/server:latest
    container_name: minetest
    command: "--gameid nodecore"
    volumes:
      - /home/docker/minetest:/config/.minetest
    ports:
      - 30000:30000/udp
    restart: unless-stopped
